dist: trusty
sudo: false
language: php
install: true

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  
notifications:
  on_success: never
  on_failure: always

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
