dist: trusty
sudo: false
language: php

notifications:
  on_success: never
  on_failure: change
  
 
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
    tags: true
